export * from "./detectFileType"
export * from "./getMinter"
export * from "./buildMetaDataArray"
export * from "./replaceIndexString"
export * from "./spiltArrayByAmount"
export * from "./validateMetadata"
